#!/bin/bash
echo "you are welcome to the new card home"
echo "is this your first time creating a project?"
read answer
echo "$answer? okay, i just want to let you know we are here to support you"
echo "i wish you have great time"
read reply 
echo "$reply? you are welcome then..."  #1st in command